namespace Dispatcher.Api.Endpoints;

public static class DiagnosticsEndpoints
{
    public static IEndpointRouteBuilder MapDiagnosticsEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/diagnostics")
            .WithTags("Diagnostics");

        group.MapGet("/exception", () =>
        {
            throw new InvalidOperationException("Diagnostic exception generated by Step 2 middleware smoke endpoint.");
        });

        return endpoints;
    }
}
