// <auto-generated />
using System;
using Dispatcher.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dispatcher.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DispatcherDbContext))]
    partial class DispatcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dispatcher.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Dispatcher.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HistoryEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Offset")
                        .HasColumnType("double precision");

                    b.Property<int>("PollIntervalMs")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<double>("Scale")
                        .HasColumnType("double precision");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Dispatcher.Domain.Tags.TagValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("current_tag_values", (string)null);
                });

            modelBuilder.Entity("Dispatcher.Domain.Devices.Device", b =>
                {
                    b.OwnsOne("Dispatcher.Domain.Devices.DeviceConnectionSettings", "ConnectionSettings", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("host");

                            b1.Property<int>("PollIntervalMs")
                                .HasColumnType("integer")
                                .HasColumnName("poll_interval_ms");

                            b1.Property<int>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("port");

                            b1.Property<int>("RetryCount")
                                .HasColumnType("integer")
                                .HasColumnName("retry_count");

                            b1.Property<string>("SnmpCommunity")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("snmp_community");

                            b1.Property<int?>("SnmpVersion")
                                .HasColumnType("integer")
                                .HasColumnName("snmp_version");

                            b1.Property<int>("TimeoutMs")
                                .HasColumnType("integer")
                                .HasColumnName("timeout_ms");

                            b1.HasKey("DeviceId");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("ConnectionSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Dispatcher.Domain.Tags.Tag", b =>
                {
                    b.OwnsOne("Dispatcher.Domain.Tags.ModbusTagAddress", "ModbusAddress", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Address")
                                .HasColumnType("integer")
                                .HasColumnName("modbus_address");

                            b1.Property<int>("ByteOrder")
                                .HasColumnType("integer")
                                .HasColumnName("modbus_byte_order");

                            b1.Property<int>("RegisterType")
                                .HasColumnType("integer")
                                .HasColumnName("modbus_register_type");

                            b1.Property<int>("UnitId")
                                .HasColumnType("integer")
                                .HasColumnName("modbus_unit_id");

                            b1.Property<int>("WordOrder")
                                .HasColumnType("integer")
                                .HasColumnName("modbus_word_order");

                            b1.HasKey("TagId");

                            b1.ToTable("tags");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.OwnsOne("Dispatcher.Domain.Tags.SnmpTagAddress", "SnmpAddress", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Oid")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("snmp_oid");

                            b1.HasKey("TagId");

                            b1.ToTable("tags");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("ModbusAddress");

                    b.Navigation("SnmpAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
